services:
  tg:
    image: local/limits-bot:latest
    restart: unless-stopped
    build:
      context: .
    environment:
      - RUST_LOG=debug
    depends_on:
      - redis
    volumes:
      - ./configs:/app/configs:ro
  redis:
    image: redis
    restart: unless-stopped
    volumes:
      - redis-data:/data
  redis-test:
    image: redis
    ports:
      - 6379:6379
volumes:
  redis-data:
